require "./Model"


module Quartz


  # Collection of validation error messages for a single record, keyed by
  # field name (the special key `"base"` is the convention for record-level
  # errors). Modeled after `ActiveModel::Errors`.
  #
  # ```
  # errors = Quartz::Errors.new
  # errors.add( "email", "can't be blank" )
  # errors.empty?         # => false
  # errors["email"]       # => ["can't be blank"]
  # errors.full_messages  # => ["email can't be blank"]
  # ```
  class Errors

    def initialize
      @messages = {} of String => Array( String )
    end

    # Records a `message` against `field`.
    def add( field : String, message : String ) : Nil
      ( @messages[field] ||= [] of String ) << message
    end

    # Messages recorded for `field`, or an empty array.
    def []( field : String ) : Array( String )
      @messages[field]? || [] of String
    end

    # Whether no error has been recorded.
    def empty? : Bool
      @messages.empty?
    end

    # Raw field => messages map.
    def messages : Hash( String, Array( String ) )
      @messages
    end

    # Flat list of `"<field> <message>"`, e.g. `["email can't be blank"]`.
    def full_messages : Array( String )
      result = [] of String
      @messages.each { |field, msgs| msgs.each { |msg| result << "#{field} #{msg}" } }
      result
    end

    def to_s( io : IO ) : Nil
      io << full_messages.join( ", " )
    end

  end

  #--------------------------------------------------------------------------

  # Validation DSL for `AModel`.
  #
  # Reopens `AModel` so the `validates` / `validate` macros are inherited by
  # every subclass, like `field`.
  #
  # ```
  # class Account < Quartz::AModel
  #   field email    : String = ""
  #   field nickname : String = ""
  #
  #   validates email,    presence: true
  #   validates nickname, length: {min: 2, max: 10}
  #   validate do |errors|
  #     errors.add( "nickname", "is reserved" ) if nickname == "admin"
  #   end
  # end
  #
  # Account.new( email: "" ).valid?  # => false
  # ```
  #
  # Each `validates` / `validate` call redefines `_quartz_validate`, chaining
  # to the previously-defined version with `previous_def`. The per-class seed
  # (generated by `macro inherited`) chains to ancestors with `super`, so all
  # inherited and own rules run in declaration order. The accessors are plain
  # method bodies with no `inherited`-time side effects, so the interpreter
  # contract holds.
  abstract class AModel

    # Declares a field validation.
    #
    # Built-in rules:
    #   - `presence: true`        — value must not be nil nor a blank `String`.
    #   - `length: {min:, max:}`  — `String` length bounds (both optional).
    #
    # ```
    # validates email,    presence: true
    # validates nickname, length: {min: 2, max: 10}
    # ```
    macro validates ( field, **opts )
      protected def _quartz_validate( errors : Quartz::Errors ) : Nil
        previous_def
        value = @{{field.id}}

        {% if opts[:presence] %}
          if value.nil?
            errors.add( {{field.id.stringify}}, "can't be blank" )
          elsif value.is_a?( String ) && value.strip.empty?
            errors.add( {{field.id.stringify}}, "can't be blank" )
          end
        {% end %}

        {% if opts[:length] %}
          {% len = opts[:length] %}
          if value.is_a?( String )
            {% if len[:min] %}
              errors.add( {{field.id.stringify}}, "is too short (minimum {{len[:min]}} characters)" ) if value.size < {{len[:min]}}
            {% end %}
            {% if len[:max] %}
              errors.add( {{field.id.stringify}}, "is too long (maximum {{len[:max]}} characters)" ) if value.size > {{len[:max]}}
            {% end %}
          end
        {% end %}
      end
    end

    #--------------------------------------------------------------------------

    # Declares a custom validation. The block receives the record's
    # `Quartz::Errors` collection (instance methods are in scope).
    #
    # ```
    # validate do |errors|
    #   errors.add( "age", "must be adult" ) if age < 18
    # end
    # ```
    macro validate ( &block )
      {% arg = block.args.empty? ? "errors".id : block.args.first %}
      protected def _quartz_validate( {{arg}} : Quartz::Errors ) : Nil
        previous_def
        {{block.body}}
      end
    end

    #--------------------------------------------------------------------------


  end


end
